export const ADD_TO_MENU_SECTION = 'ADD_TO_MENU_SECTION'
export const SELECT_MENU_SECTION_ID = 'SELECT_MENU_SECTION_ID'

export const ADD_TO_ITEMS = 'ADD_TO_ITEMS'
export const SELECT_ITEMS_ID = 'SELECT_ITEMS_ID'

export const ADD_TO_ITEM_OPTIONS = 'ADD_TO_ITEM_OPTIONS'
export const SELECT_ITEM_OPTIONS_ID = 'SELECT_ITEM_OPTIONS_ID'

export const ADD_TO_OPTION_CHOICES = 'ADD_TO_OPTION_CHOICES'

export const CURRENT_FORM_INPUT = 'CURRENT_FORM_INPUT'

export const SHOW_MODAL = 'SHOW_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'

export const UPDATE_NAME = 'UPDATE_NAME'
export const UPDATE_TITLE = 'UPDATE_TITLE'
export const UPDATE_PRICE = 'UPDATE_PRICE'

export const UPDATE_ID = 'UPDATE_ID'